-- ============================================================
-- ProteinaSmart: datos iniciales para Supabase/PostgreSQL.
-- Ejecutar despues de supabase/schema.sql en el SQL Editor completo.
-- El contrato coincide con js/catalog.js y con adaptarProducto en js/data-source.js.

insert into public.categorias(nombre, slug)
values
  ('Proteínas', 'proteinas'),
  ('Deportivos', 'deportivos'),
  ('Keto / Low carb', 'keto'),
  ('Salud & Longevidad', 'longevidad');

insert into public.productos (
  nombre,
  descripcion,
  precio,
  unidad_medida,
  categoria,
  objetivos,
  disciplinas,
  imagen,
  stock,
  protocolo,
  complemento,
  etiquetas
)
values
  (
    'Whey Protein Isolate',
    '27 g de proteína por scoop, sin lactosa y con carga glucémica mínima.',
    330000,
    '2 lb · 27 servicios',
    'proteinas',
    array['masa', 'definicion']::text[],
    array['healthy-habits', 'low-carb']::text[],
    null,
    true,
    'Ganar masa',
    'Creatina + EAA',
    array['Más vendido']::text[]
  ),
  (
    'Whey Protein Concentrada',
    'El mejor costo por gramo de proteína para volumen sostenido.',
    450000,
    '5 lb · 68 servicios',
    'proteinas',
    array['masa']::text[],
    array['healthy-habits', 'low-carb']::text[],
    null,
    true,
    'Ganar masa',
    'Creatina + EAA',
    '{}'::text[]
  ),
  (
    'Proteína Vegetal (arveja + arroz)',
    'Perfil de aminoácidos completo, sin lácteos ni gluten. Digestión liviana.',
    265000,
    '1 kg · 30 servicios',
    'proteinas',
    array['definicion', 'masa']::text[],
    array['healthy-habits', 'low-carb']::text[],
    null,
    true,
    'Bajar grasa / Definir',
    'EAA + Aceite MCT',
    '{}'::text[]
  ),
  (
    'Colágeno Hidrolizado + Vitamina C',
    'Péptidos tipo I y III para piel, cabello, uñas y articulaciones.',
    215000,
    '300 g · 30 servicios',
    'proteinas',
    array['belleza']::text[],
    array['healthy-habits', 'low-carb']::text[],
    null,
    true,
    'Belleza & longevidad',
    'Omega 3 + Vitamina D3+K2',
    array['Belleza & longevidad']::text[]
  ),
  (
    'Creatina Monohidratada Micronizada',
    'El suplemento con más evidencia: fuerza, masa magra y función cognitiva.',
    235000,
    '300 g · 100 servicios',
    'deportivos',
    array['masa', 'foco', 'energia']::text[],
    array['healthy-habits']::text[],
    null,
    true,
    'Ganar masa',
    'Whey Protein + EAA',
    array['Base de todo']::text[]
  ),
  (
    'Pre-Entreno sin azúcar',
    'Cafeína, beta-alanina y citrulina. Cero carbohidratos, apto keto.',
    255000,
    '300 g · 30 servicios',
    'deportivos',
    array['energia', 'foco']::text[],
    array['healthy-habits']::text[],
    null,
    true,
    'Energía sostenida',
    'Aceite MCT + Vitamina D3+K2',
    '{}'::text[]
  ),
  (
    'Aminoácidos Esenciales (EAA)',
    'Protege masa muscular durante el ayuno y los déficits calóricos.',
    185000,
    '400 g · 40 servicios',
    'deportivos',
    array['definicion', 'masa']::text[],
    array['healthy-habits']::text[],
    null,
    true,
    'Bajar grasa / Definir',
    'Whey Protein Vegetal + MCT',
    '{}'::text[]
  ),
  (
    'L-Glutamina',
    'Recuperación muscular e integridad intestinal en entrenamientos exigentes.',
    145000,
    '300 g · 60 servicios',
    'deportivos',
    array['definicion']::text[],
    array['healthy-habits']::text[],
    null,
    true,
    'Recuperación muscular',
    'Whey Protein + Creatina',
    '{}'::text[]
  ),
  (
    'Aceite MCT C8/C10',
    'Energía cetónica inmediata sin picos de insulina. Ideal en el café matinal.',
    185000,
    '500 ml',
    'keto',
    array['energia', 'foco']::text[],
    array['keto', 'low-carb']::text[],
    null,
    true,
    'Energía sostenida',
    'Vitamina D3+K2 + Pre-entreno',
    array['Keto esencial']::text[]
  ),
  (
    'Barras Keto (caja x 12)',
    'Snack real para cortar el hambre sin romper la cetosis.',
    145000,
    '12 u · 2 g carbos netos',
    'keto',
    array['definicion']::text[],
    array['keto', 'low-carb']::text[],
    null,
    true,
    'Keto / Low carb',
    'Aceite MCT + Sustituto de Comida',
    '{}'::text[]
  ),
  (
    'Sustituto de Comida Low Carb',
    'Comida completa en 400 kcal: proteína, grasas buenas y fibra.',
    295000,
    '1 kg · 20 servicios',
    'keto',
    array['definicion']::text[],
    array['keto', 'low-carb']::text[],
    null,
    true,
    'Keto / Low carb',
    'Aceite MCT + Proteína Vegetal',
    '{}'::text[]
  ),
  (
    'Endulzante Monk Fruit + Eritritol',
    'Cero índice glucémico, sin regusto. Reemplazo directo del azúcar.',
    89000,
    '250 g',
    'keto',
    array['definicion']::text[],
    array['keto', 'low-carb']::text[],
    null,
    true,
    'Keto / Low carb',
    'Aceite MCT + Barras Keto',
    '{}'::text[]
  ),
  (
    'Omega 3 Ultra (EPA/DHA)',
    'DHA de alta concentración: membrana neuronal, memoria y antiinflamación.',
    169000,
    '120 cápsulas',
    'longevidad',
    array['foco', 'belleza']::text[],
    array['neuroplasticidad', 'healthy-habits']::text[],
    null,
    true,
    'Foco y claridad mental',
    'Magnesio Glicinato + Nootrópico Focus',
    array['Neuroplasticidad']::text[]
  ),
  (
    'Magnesio Glicinato',
    'Sueño profundo y recuperación nerviosa. La forma que sí se absorbe.',
    165000,
    '120 cápsulas',
    'longevidad',
    array['foco', 'energia']::text[],
    array['neuroplasticidad', 'healthy-habits']::text[],
    null,
    true,
    'Foco y claridad mental',
    'Omega 3 + Nootrópico Focus',
    '{}'::text[]
  ),
  (
    'Vitamina D3 + K2',
    'Hueso, inmunidad y testosterona. El déficit más común y más barato de corregir.',
    145000,
    '90 cápsulas',
    'longevidad',
    array['belleza', 'energia']::text[],
    array['neuroplasticidad', 'healthy-habits']::text[],
    null,
    true,
    'Energía sostenida',
    'Aceite MCT + Omega 3',
    '{}'::text[]
  ),
  (
    'Nootrópico Focus (L-teanina + colina)',
    'Concentración sostenida sin ansiedad ni bajón posterior.',
    195000,
    '60 cápsulas',
    'longevidad',
    array['foco']::text[],
    array['neuroplasticidad', 'healthy-habits']::text[],
    null,
    true,
    'Foco y claridad mental',
    'Omega 3 + Magnesio Glicinato',
    array['Nuevo']::text[]
  );