#!/bin/bash
# ============================================================
# IMPLEMENTATION SCRIPT - Paraguay Future Invest Monetization
# Ejecuta este script paso a paso (NO todo de una)
# ============================================================

# ANTES DE EMPEZAR:
# - Ten abierta una pestaña en Mailchimp, Calendly y Google Analytics
# - Ten a mano: tu email real, número de WhatsApp, URL del sitio

echo "🚀 IMPLEMENTACIÓN - Paraguay Future Invest Monetization"
echo "========================================================"
echo ""
echo "FASE 1: CONFIGURAR MAILCHIMP"
echo "----------------------------"
echo ""
echo "⏸️  PAUSA AQUÍ Y SIGUE ESTOS PASOS EN MAILCHIMP:"
echo ""
echo "1. Ve a https://mailchimp.com → Sign Up"
echo "2. Completa el registro con tu email"
echo "3. Una vez adentro, crea una nueva 'Audience' (audiencia):"
echo "   - Nombre: 'Paraguay Future Invest'"
echo "   - Email to send from: tu-email@tudominio.com"
echo "   - Default from name: Oscar (o tu nombre)"
echo "4. Ve a Settings → Audience defaults"
echo "   - Habilita: Double opt-in (más confiable)"
echo "5. Ve a Settings → Reply-to email"
echo "   - Pon tu email real"
echo ""
echo "✅ Cuando termines, presiona ENTER"
read -p ""

echo ""
echo "6. OBTENER EL CÓDIGO DEL FORMULARIO:"
echo "   - En Mailchimp, ve a 'Signup forms' → Embedded forms"
echo "   - Copia el código HTML del formulario (todo el <form>)"
echo "   - Pégalo en tu archivo index.html en el lugar donde dice 'leadForm'"
echo ""
echo "⏸️  Haz esto ahora. Presiona ENTER cuando termines."
read -p ""

echo ""
echo "FASE 2: CONFIGURAR CALENDLY"
echo "----------------------------"
echo ""
echo "1. Ve a https://calendly.com → Sign Up"
echo "2. Completa el registro"
echo "3. Conecta tu Google Calendar (dale permiso)"
echo "4. Crea 2 tipos de citas:"
echo ""
echo "   a) SESIÓN ESTRATEGIA"
echo "      - Nombre: 'Sesión Estrategia - 90 min'"
echo "      - Duración: 90 minutos"
echo "      - Precio: \$300 USD"
echo "      - Descripción: 'Análisis personalized de tu perfil inversor + roadmap 12 meses'"
echo ""
echo "   b) CONSULTA GRATIS"
echo "      - Nombre: 'Consulta Inicial - 30 min'"
echo "      - Duración: 30 minutos"
echo "      - Precio: GRATIS"
echo "      - Descripción: 'Exploración inicial - sin compromiso'"
echo ""
echo "5. Para cada una, copia el link único (ej: calendly.com/oscar/estrategia)"
echo ""
echo "⏸️  Cuando tengas ambos links, presiona ENTER"
read -p ""

echo ""
echo "FASE 3: CREAR PÁGINA DE SERVICIOS"
echo "----------------------------------"
echo ""
echo "1. En tu carpeta, crea: servicios.html"
echo "2. Copia el contenido de marketing/03_pagina-servicios-pagos.html"
echo "3. Reemplaza los botones con tus links de Calendly:"
echo ""
echo "   BUSCA: 'AGENDAR AHORA' (primera consulta)"
echo "   REEMPLAZA CON: <a href='https://calendly.com/TU-USERNAME/estrategia' target='_blank'>"
echo ""
echo "   BUSCA: 'CONTRATAR' (due diligence)"
echo "   REEMPLAZA CON: <a href='https://calendly.com/TU-USERNAME/diligencia' target='_blank'>"
echo ""
echo "4. Reemplaza el email en footer: contacto@proteinasmart.com → TU-EMAIL"
echo ""
echo "⏸️  Cuando termines, presiona ENTER"
read -p ""

echo ""
echo "FASE 4: CONFIGURAR GOOGLE ANALYTICS"
echo "------------------------------------"
echo ""
echo "1. Ve a https://analytics.google.com"
echo "2. Haz clic en 'Empezar a medir'"
echo "3. Nombre propiedad: 'Paraguay Future Invest Landing'"
echo "4. Crea una cuenta (o usa la existente)"
echo "5. Copia tu 'ID de medición' (empieza con G-)"
echo "6. En index.html, busca la línea: <!-- Google Analytics -->"
echo "7. Reemplaza 'G-XXXXXXXXXX' con tu ID real"
echo ""
echo "✅ El código ya está en index.html, solo reemplaza el ID"
echo ""
echo "⏸️  Presiona ENTER cuando termines"
read -p ""

echo ""
echo "FASE 5: CONFIGURAR AUTOMATIZACIÓN DE EMAILS"
echo "--------------------------------------------"
echo ""
echo "1. En Mailchimp, ve a 'Automations' → 'Create Workflow'"
echo "2. Selecciona 'When someone subscribes to a list'"
echo "3. Crea una workflow con 5 emails:"
echo ""
echo "   EMAIL 1 (0 minutos después de suscripción):"
echo "   - Asunto: 'Tu acceso al Dossier está listo 🔓'"
echo "   - Copy: Ver en marketing/02_secuencia-emails-5-partes.md (EMAIL 1)"
echo "   - Incluye link para descargar el dossier"
echo ""
echo "   EMAIL 2 (+2 días):"
echo "   - Asunto: 'El error #1 que te hará perder dinero'"
echo "   - Copy: marketing/02_secuencia-emails-5-partes.md (EMAIL 2)"
echo ""
echo "   EMAIL 3 (+4 días):"
echo "   - Asunto: 'De 50k a 180k en 3 años (historia real)'"
echo "   - Copy: marketing/02_secuencia-emails-5-partes.md (EMAIL 3)"
echo ""
echo "   EMAIL 4 (+7 días):"
echo "   - Asunto: '¿Es Paraguay un mercado seguro para invertir?'"
echo "   - Copy: marketing/02_secuencia-emails-5-partes.md (EMAIL 4)"
echo ""
echo "   EMAIL 5 (+10 días):"
echo "   - Asunto: 'Acceso VIP: Nuevos proyectos ANTES que otros'"
echo "   - Copy: marketing/02_secuencia-emails-5-partes.md (EMAIL 5)"
echo ""
echo "4. Habilita 'Wait between emails' para que sean secuenciales"
echo ""
echo "⏸️  Cuando termines la workflow, presiona ENTER"
read -p ""

echo ""
echo "FASE 6: TESTEO INICIAL"
echo "----------------------"
echo ""
echo "1. Abre tu landing en navegador: http://localhost:5500 (o tu URL)"
echo "2. Completa el formulario con datos de test"
echo "3. Verifica:"
echo "   ✓ Recibes email de Mailchimp (chequea spam también)"
echo "   ✓ El email es del Mailchimp automático que creaste"
echo "   ✓ Después de 2 días, recibirás el Email 2 (o crea una segunda suscripción de test)"
echo ""
echo "4. Prueba el link de Calendly:"
echo "   ✓ Haz clic en 'AGENDAR CONSULTA'"
echo "   ✓ Verifica que abra Calendly correctamente"
echo ""
echo "5. Verifica que los datos lleguen a Google Analytics:"
echo "   ✓ Ve a Google Analytics → Realtime"
echo "   ✓ Abre tu sitio en nueva pestaña"
echo "   ✓ Deberías ver '1 visitor' en realtime"
echo ""
echo "⏸️  Cuando todo esté testeado, presiona ENTER"
read -p ""

echo ""
echo "FASE 7: ACTUALIZAR LANDING CON COPY MEJORADO"
echo "---------------------------------------------"
echo ""
echo "1. Abre marketing/01_copy-landing-mejorada.md"
echo "2. Reemplaza en index.html:"
echo ""
echo "   HERO SECTION (título principal)"
echo "   FROM: 'Oportunidades de Inversión en Paraguay'"
echo "   TO: Ver en 01_copy-landing-mejorada.md → HERO SECTION"
echo ""
echo "   SUBHEADER (promesa de valor)"
echo "   FROM: tu copy actual"
echo "   TO: Ver 01_copy-landing-mejorada.md → SUBHEADER"
echo ""
echo "   CTA SECUNDARIO (antes del footer)"
echo "   ADD: Ver 01_copy-landing-mejorada.md → CTA SECUNDARIO"
echo ""
echo "3. Guarda y recarga la página"
echo ""
echo "⏸️  Presiona ENTER cuando termines"
read -p ""

echo ""
echo "FASE 8: CREAR SHEET DE TRACKING"
echo "--------------------------------"
echo ""
echo "1. Ve a https://sheets.google.com"
echo "2. Crea nuevo spreadsheet: 'PFI - Marketing Dashboard'"
echo "3. Crea las TABs:"
echo "   - Tab 1: 'Resumen Ejecutivo'"
echo "   - Tab 2: 'Email Marketing'"
echo "   - Tab 3: 'Landing Analytics'"
echo "   - Tab 4: 'Pipeline de Ventas'"
echo "   - Tab 5: 'Ingresos'"
echo ""
echo "4. Usa las estructuras en marketing/06_dashboard-metricas-template.md"
echo "5. Comparte el link contigo mismo para acceso desde cualquier lado"
echo ""
echo "⏸️  Cuando termines, presiona ENTER"
read -p ""

echo ""
echo "FASE 9: BACKUP Y GIT COMMIT"
echo "----------------------------"
echo ""
echo "1. Abre terminal en tu carpeta proteinasmart"
echo ""
echo "   git add ."
echo "   git commit -m 'feat: add monetization setup - mailchimp, calendly, servicios'"
echo "   git push origin main"
echo ""
echo "✅ Todo guardado en tu repo"
echo ""

echo ""
echo "🎉 ¡IMPLEMENTACIÓN COMPLETADA!"
echo "================================"
echo ""
echo "PRÓXIMOS PASOS (LANZAMIENTO):"
echo ""
echo "1. Comparte landing con 20-30 personas de confianza"
echo "   - Pide feedback: ¿se ve bien? ¿entendés qué ofrezco?"
echo ""
echo "2. Monitorea las primeras 2 semanas:"
echo "   - Actualiza dashboard cada viernes"
echo "   - Revisa tasa de conversión (meta: >5%)"
echo "   - Revisa tasa apertura de emails (meta: >30%)"
echo ""
echo "3. Realiza primeras consultas:"
echo "   - Cuando alguien agende en Calendly, confirmá por WhatsApp"
echo "   - Realiza la sesión de 30-90 min"
echo "   - Documenta si se convirtió a cliente pagado"
echo ""
echo "4. Test A/B (después de 50 suscriptores):"
echo "   - Prueba 2 asuntos diferentes en Email 1"
echo "   - Prueba 2 colors diferentes en CTA"
echo "   - Implementa el que gane"
echo ""
echo "💡 RECURSOS:"
echo "   - Checklist completo: marketing/04_plan-implementacion-checklist.md"
echo "   - Dashboard template: marketing/06_dashboard-metricas-template.md"
echo "   - Afiliados & patrocinios: marketing/05_afiliados-patrocinios-templates.md"
echo ""
echo "📞 SOPORTE:"
echo "   Si algo no funciona, revisa:"
echo "   1. ¿El form de Mailchimp está bien pegado?"
echo "   2. ¿Los links de Calendly son correctos?"
echo "   3. ¿Google Analytics tiene el ID correcto?"
echo ""
echo "¡Adelante con el lanzamiento! 🚀"
echo ""
